#SERVER PORT
server:
  port: 8070

#SPRING PROPS
spring:
  application:
    name: security-app
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 380406904202969
            clientSecret: c0d6ddef5ea359c6747c6ead9eec8f1c
            scope:
              - email
              - public_profile
          google:
            clientId: 712056738368-vdgcumqhctjgnspbt1vgr6ajjdsiuvqg.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          github:
            clientId: Iv1.c9dafd6635a9e45f
            clientSecret: 436965a0b0f24848d11bc534d72801924e1644cc
            scope:
              - read:user
              - user:email
    filter:
      order: 5
    user:
      password: 123456
#Actuator props
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'

#Logger props
logging:
  level:
#    org.springframework.security: trace
    root: info

authorizedRedirectUris: http://localhost:8070/home