#SERVER PORT
server:
  port: 8070
#SPRING PROPS
spring:
  application:
    name: security-app
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
#Actuator props
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'

#Logger props
logging:
  level:
    root: info